@startuml first_diagram
Alice -> Bob: Authentication Request [[#second_diagram]]
Bob -> Alice: Authentication Response
@enduml

@startuml second_diagram
actor User
User -> System: Do something
@enduml
