name: Check PlantUML Diagrams

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-plantuml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check PlantUML syntax
      run: npx plantuml-cli -checksyntax wiki/diagrams.puml
