name: Publish to Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - '.github/workflows/publish-wiki.yml'

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki
